media:
  - name: images
    label: Images
    input: src/content/gallery
    output: /src/content/gallery
    extensions: [ jpeg, jpg, png ]

content:
  - name: blog
    label: Blog
    path: src/content/blog
    type: collection
    filename: '{year}-{month}-{day}-{primary}.mdx'
    view:
      fields: [ title ]
      primary: title
      sort: [ datum, title ]
      default:
        search: ''
        sort: title
        order: desc